### ISSUE TITLE
Support for groovy change -> customChange

### ISSUE THREAD

**Issue by ErwinvanBrandwijk** [tlberglund/groovy-liquibase#2]
There is now a customChange without code.
It should allow:

- Groovy code, that will only be executed if it's in the customChange.
- accessibility to the database. SQL.
- Possibility to use the re factorings from liquibase in the customChange, example addColumn.

You could take a look at the grails plugin, he has a GrailsChange.

**Comment by stevesaliman** [comment]
This is a pretty old issue.  Is this still needed?  

The code for this project has moved, so if this is still needed, please open a new issue in https://github.com/liquibase/liquibase-groovy-dsl
