### ISSUE TITLE
include does not work relative from changelog file

### ISSUE THREAD

**Issue by jeroenvs** [tlberglund/groovy-liquibase#22]
Whenever a file resource accessor is used with a custom base path, include statements no longer work. This is because the include parser does not use the resource accessor, but new File(params.path), which has no knowledge of our base directory.

Code (DatabaseChangeLogDelegate.groovy - line 94 ~ 101):

def files = []
new File(params.path).eachFileMatch(~/.*.groovy/) { file->
 files << file.path
}

files.sort().each { filename ->
 includeChangeLog(filename)
}

**Comment by stevesaliman** [comment]
Is this still an issue?

**Comment by stevesaliman** [comment]
Closing due to age. If this is still an issue, please open a new issue in the new repository for this project,  https://github.com/liquibase/liquibase-groovy-dsl
