### ISSUE TITLE
modifySql tag

### ISSUE THREAD

**Issue by ErwinvanBrandwijk** [tlberglund/groovy-liquibase#6]
modifySql tag isn't supported.

It's used to add sql to a generated SQL script.
Example:
    createTable(tableName: "projects"){
         column(name: "id", type: "bigint(20)"){
              constraints(nullable: "false", primaryKey: "true")
         }
         column(name: "project_name", type: "varchar(50)")
     }
     modifySql{
         append(value: " DEFAULT CHARSET=utf8")
    }

It adds default charset at the end of sql script from create table.
Other possibilities

* replace

* prepend

http://www.liquibase.org/manual/modify_sql

**Comment by stevesaliman** [comment]
The 1.0 releases of the DSL support the modifySql change.
